### ISSUE TITLE
[1.0] Numpad not working X11/KDE

### ISSUE THREAD

**Issue by alexheretic** [big-ab-games/robo-instructus#202]

**Comment by Friz64** [comment]
Hello! I'm the guy that left that comment on reddit. I just launched the game again to **really** confirm this and the numpad magically works now, although i'm unsure why. I think you can close this. 

Sorry for the inconvenience, and again really nice work.

**Comment by alexheretic** [comment]
Ok I'll close for now & look out for further reports, thanks for the update.
