### ISSUE TITLE
Is a run size of 9 really possible in the very first level?

### ISSUE THREAD

**Issue by bert2** [big-ab-games/robo-instructus#204]
Congratulations for releasing this nice game!

I'm wondering if the best run size of 9 really is possible for the very first level. I can't think of a way to do better than this:

![image](https://user-images.githubusercontent.com/1454629/61327059-5e858180-a818-11e9-9092-42331f0367f6.png)

I'm not asking for the solution (if there is one), I just want to know if it's possible, because it's driving me crazy 😄

**Comment by alexheretic** [comment]
That `Best 9` means _your_ best run score was 9 phrases. So yes it's absolutely possible you are the proof ;).

_Run_ is about how many "phases" the interpreter has to execute before completing the level. In this case `loop` is one of those phrases. If you lose that you'll simplify the _Run_ whilst increasing the _Solution_ size.

A little later on in the game you'll be able to switch between your best scoring solutions for any level, as these are automatically saved.

**Comment by bert2** [comment]
Oh I see, so it's exactly like the loop unrolling optimization compilers might do to reduce the number of branch instructions. Thanks for the explanation!
