### ISSUE TITLE
[1.0] release ost

### ISSUE THREAD

**Issue by alexheretic** [big-ab-games/robo-instructus#205]

**Comment by murlakatamenka** [comment]
Submit [vgmdb](https://vgmdb.net/) entry while doing so. Or ping me and I'll add it myself :)

**Comment by alexheretic** [comment]
It's now available for all game owners, see https://github.com/big-ab-games/robo-instructus/releases/tag/1.4

@murlakatamenka let me know if you need any more info

**Comment by murlakatamenka** [comment]
https://vgmdb.net/album/89286

You can add a cover to the entry.
