### ISSUE TITLE
Screen flashing during text screens

### ISSUE THREAD

**Issue by AlexDikelsky** [big-ab-games/robo-instructus#206]
On the text screens, the screen flashes white. I'm using Windows, and on a very small screen

![bug](https://user-images.githubusercontent.com/52082790/61382456-725dd180-a872-11e9-9f42-0b6a20683ed7.gif)

**Comment by alexheretic** [comment]
Thanks for the report. Can you tell me what gpu & drivers you are using, and is this happening consistently?

**Comment by AlexDikelsky** [comment]
Intel(R) UHD Graphics 620, and the driver version is 24.20.100.6286
I'm on Windows 64 bit.
It happened on other text screens as well.

**Comment by alexheretic** [comment]
Thanks, I suspect this is related to the intel opengl driver. If it's possible can you ensure you have the latest intel drivers? I'll try to get hold of an intel gpu setup and reproduce this bug.

**Comment by alexheretic** [comment]
I've done a run of testing with an Intel HD 4600 but I failed to reproduce these errors. It looks like driver _26.20.100.6912_ is the latest for the 620. Maybe it'll help?

**Comment by alexheretic** [comment]
I guess I failed to reproduce this, so I'll close unless new info comes to light.
