### ISSUE TITLE
Demo doesn't have a "cover" image

### ISSUE THREAD

**Issue by AlexDikelsky** [big-ab-games/robo-instructus#215]
It says "no image available" for the demo. I don't know if this is necessarily bad.
![image](https://user-images.githubusercontent.com/52082790/61537167-0e671480-a9fc-11e9-8ef1-8a8edef4ea44.png)

**Comment by alexheretic** [comment]
Thanks for reporting this. The demo must be missing an asset in the steam db. Shouldn't be too hard to fix.

**Comment by alexheretic** [comment]
I've added the missing asset now, I think. It should be fixed if you restart steam.

**Comment by AlexDikelsky** [comment]
Just checked, it looks right now.

<img width="494" alt="nwef" src="https://user-images.githubusercontent.com/52082790/61548214-c69fb780-aa12-11e9-9778-23ed99a1bcea.PNG">

**Comment by alexheretic** [comment]
Thanks for re-checking!
