### ISSUE TITLE
Text in comments

### ISSUE THREAD

**Issue by lgb** [big-ab-games/robo-instructus#230]
Hi!

Currently game supports only English text in code screen. It's fun because in translation we translate comments in code, but user can't do that comments - he cant type non-Latin letters. Cyrillic for example.

**Comment by alexheretic** [comment]
Yes I can see how this could happen, I'll take a look at this in the coming week. I think the code editor should support non-latin ok in most senses, ie you can paste it in and it'll render/layout ok. So, if my hunch is right, it's just the character/typing input that needs looking at.

**Comment by alexheretic** [comment]
The entry logic was allowing only printable ascii characters _32-126_. The next release will continue to filter out the first 32 & 127 but allow everything else. This will allow Cyrillic chars and any other 32bit unicode.
