### ISSUE TITLE
Missing newline on copy/paste

### ISSUE THREAD

**Issue by tanriol** [big-ab-games/robo-instructus#243]
If I cut a whole line or several (Shift+Down, Ctrl+X) and then try to paste it somewhere with Ctrl+V, the final newline is lost, so the last pasted line is merged with the following line. That's a bit uncomfortable :-(

P.S. Thanks for a really interesting game :-)

**Comment by alexheretic** [comment]
Thanks for reporting this, I will investigate.

**Comment by alexheretic** [comment]
This will be fixed in the next update
